//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("3.3.0.0")]
[assembly: AssemblyFileVersion("3.3.1.0")]
[assembly: AssemblyConfiguration("Debug built on 2014-04-26 00:35")]
[assembly: AssemblyCopyright("Copyright @ 2014 Autofac Contributors")]
[assembly: AssemblyInformationalVersion("3.3.1-alpha")]
[assembly: AssemblyDescription("Autofac 3.3.1-alpha")]


