//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("3.3.0.0")]
[assembly: AssemblyFileVersion("3.3.0.0")]
[assembly: AssemblyConfiguration("Debug built on 2014-05-06 00:53")]
[assembly: AssemblyCopyright("Copyright @ 2014 Tokiota SL")]
[assembly: AssemblyInformationalVersion("1.0.0-alpha")]
[assembly: AssemblyDescription("Tokiota.Toolkit.StringExtensions 1.0.0-alpha")]


